2025-09-20 15:43:16.201 | INFO     | Логирование настроено. Файл: C:\Users\disag\PycharmProjects\face_recognition\app\logs\app.txt
2025-09-20 15:43:16.218 | INFO     | Started server process [19852]
2025-09-20 15:43:16.218 | INFO     | Started server process [19852]
2025-09-20 15:43:16.218 | INFO     | Waiting for application startup.
2025-09-20 15:43:16.218 | INFO     | Waiting for application startup.
2025-09-20 15:43:16.265 | INFO     | [startup] Весовые файлы доступны в: C:\Users\disag\PycharmProjects\face_recognition\app\.deepface\weights
2025-09-20 15:43:16.265 | INFO     | Загрузка модели 'Facenet'
2025-09-20 15:43:21.186 | INFO     | [startup] Модель 'Facenet' загружена
2025-09-20 15:43:21.186 | INFO     | [startup] Watchdog запущен (interval=600s)
2025-09-20 15:43:22.095 | INFO     | Application startup complete.
2025-09-20 15:43:22.096 | INFO     | Application startup complete.
2025-09-20 15:43:37.116 | INFO     | 127.0.0.1:50727 - "GET /docs HTTP/1.1" 200
2025-09-20 15:43:37.209 | INFO     | 127.0.0.1:50727 - "GET /openapi.json HTTP/1.1" 200
2025-09-20 15:43:58.510 | INFO     | 127.0.0.1:50728 - "POST /verify?threshold=0.7 HTTP/1.1" 200
2025-09-20 15:43:59.991 | INFO     | 127.0.0.1:50728 - "POST /verify?threshold=0.7 HTTP/1.1" 200
2025-09-20 15:44:14.513 | INFO     | Shutting down
2025-09-20 15:44:14.513 | INFO     | Shutting down
2025-09-20 15:44:14.624 | INFO     | Waiting for application shutdown.
2025-09-20 15:44:14.624 | INFO     | Waiting for application shutdown.
2025-09-20 15:44:14.628 | ERROR    | Traceback (most recent call last):
  File "C:\Users\disag\PycharmProjects\face_recognition\.venv\Lib\site-packages\starlette\routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\Users\disag\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 217, in __aexit__
    await anext(self.gen)
  File "C:\Users\disag\PycharmProjects\face_recognition\.venv\Lib\site-packages\fastapi\routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "C:\Users\disag\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 217, in __aexit__
    await anext(self.gen)
  File "C:\Users\disag\PycharmProjects\face_recognition\app\main.py", line 50, in lifespan
    await task
  File "C:\Users\disag\PycharmProjects\face_recognition\app\utils\watchdog.py", line 48, in watchdog_task
    await asyncio.sleep(settings.watchdog_interval_sec)
  File "C:\Users\disag\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 649, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError

2025-09-20 15:44:14.628 | ERROR    | Traceback (most recent call last):
  File "C:\Users\disag\PycharmProjects\face_recognition\.venv\Lib\site-packages\starlette\routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\Users\disag\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 217, in __aexit__
    await anext(self.gen)
  File "C:\Users\disag\PycharmProjects\face_recognition\.venv\Lib\site-packages\fastapi\routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "C:\Users\disag\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 217, in __aexit__
    await anext(self.gen)
  File "C:\Users\disag\PycharmProjects\face_recognition\app\main.py", line 50, in lifespan
    await task
  File "C:\Users\disag\PycharmProjects\face_recognition\app\utils\watchdog.py", line 48, in watchdog_task
    await asyncio.sleep(settings.watchdog_interval_sec)
  File "C:\Users\disag\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 649, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError

2025-09-20 15:44:14.628 | ERROR    | Application shutdown failed. Exiting.
2025-09-20 15:44:14.628 | ERROR    | Application shutdown failed. Exiting.
2025-09-20 15:44:14.628 | INFO     | Finished server process [19852]
2025-09-20 15:44:14.628 | INFO     | Finished server process [19852]
